const colors = require('colors');

const handleError = async (
  response,
  fallbackMessage = 'An unexpected error occured. Please try again in a moment.',
  transformMessage
) => {
  let json, message;

  try {
    json = await response.json();
    message = json.error?.message;
    if (message && transformMessage) {
      message = transformMessage(message);
    }
  } catch (e) {}

  if (!message) {
    message = fallbackMessage;
  }

  console.log(colors.red(message));
  process.exit(1);
};

module.exports = handleError;
